### ISSUE TITLE
Did not want to compile - "stod" was not declared

### ISSUE THREAD

**Issue by pikawolfy** [dabe5651/Bernstien_CSCI2270_FinalProject#2]
I believe if you want to use stod in your main.cpp, you need to abide by std rules and write std::stod. The program didn't want to compile because of this.

**Comment by dabe5651** [comment]
There are many issues with the code but I have it running fine in
codeblocks. I just added your suggestion and it ran the same, thanks for
the advice.

**Comment by pikawolfy** [comment]
When I am trying it through codeblocks, it is telling me that "stod" is not declared in the scope..

**Comment by pikawolfy** [comment]
I fixed it for my CodeBlocks - you may want to include this in the ReadMe. I had to go to Settings -> Compiler -> "Have g++ follow the C++ 11 ISO...".
